import type { Sticker } from '../types';

export const STICKERS: Sticker[] = [
  {
    id: 'starknight',
    name: 'STAR KNIGHT',
    rarity: 'common',
    bg: 'linear-gradient(135deg,#3da5ff,#b83dff)',
    pixels: [
      '.....KKKKKK.....',
      '....KYYYYYYK....',
      '...KYWYYYYWYK...',
      '...KYYYYYYYYK...',
      '....KYWYYWYK....',
      '....KYYYYYYK....',
      '...KKDDDDDDKK...',
      '..KDDWDDDDWDDK..',
      '..KDDDDDDDDDDK..',
      '..KDDDRDDRDDDK..',
      '...KDDDDDDDDK...',
      '....KNDDDDNK....',
      '....KN.KK.NK....',
      '....KN.KK.NK....',
      '...KYY.KK.YYK...',
      '...KKK....KKK...',
    ],
  },
  {
    id: 'lasersword',
    name: 'LASER SABER',
    rarity: 'common',
    bg: 'linear-gradient(135deg,#0a0a14,#2d2d5c)',
    pixels: [
      '.............CC.',
      '............CWC.',
      '...........CWC..',
      '..........CWC...',
      '.........CWC....',
      '........CWC.....',
      '.......CWC......',
      '......CWC.......',
      '.....CWC........',
      '....CWC.........',
      '...CWC..........',
      '..CWC...........',
      '.KSK............',
      'KSSSK...........',
      'KSKSK...........',
      '.KKK............',
    ],
  },
  {
    id: 'robopal',
    name: 'ROBO-PAL R3',
    rarity: 'common',
    bg: 'linear-gradient(135deg,#ffd93d,#ff7a1f)',
    pixels: [
      '.....KKKKKK.....',
      '....KDDDDDDK....',
      '...KDDDDDDDDK...',
      '..KDDKKDDKKDDK..',
      '..KDDKCKDKCKDDK.',
      '..KDDKKDDKKDDK..',
      '...KDDDRRDDDK...',
      '....KDDDDDDK....',
      '...KSSSSSSSSK...',
      '..KSSCSSSSCSSK..',
      '..KSSSSSSSSSSK..',
      '..KSSCCCCCCSSK..',
      '..KSSSSSSSSSSK..',
      '...KSS....SSK...',
      '....KK....KK....',
      '....KK....KK....',
    ],
  },
  {
    id: 'fighter',
    name: 'X-FIGHTER',
    rarity: 'rare',
    bg: 'linear-gradient(135deg,#ff2e63,#b83dff)',
    pixels: [
      'K..............K',
      'KK............KK',
      'KSK..........KSK',
      'KCSK........KSCK',
      'KSCSK......KSCSK',
      '.KSCSKKKKKKSCSK.',
      '..KSCSDDDDSCSK..',
      '...KSDWWWWDSK...',
      '...KSDCCCCDSK...',
      '...KSDWWWWDSK...',
      '..KSCSDDDDSCSK..',
      '.KSCSKKKKKKSCSK.',
      'KSCSK......KSCSK',
      'KCSK........KSCK',
      'KSK..........KSK',
      'K..............K',
    ],
  },
  {
    id: 'alien',
    name: 'BLIP ALIEN',
    rarity: 'rare',
    bg: 'linear-gradient(135deg,#3ce67a,#4cf1ff)',
    pixels: [
      '.....KKKKKK.....',
      '....KGGGGGGK....',
      '...KGGCGGCGGK...',
      '...KGCKGGKCGK...',
      '...KGGCGGCGGK...',
      '....KGGGGGGK....',
      '.....KGRRGK.....',
      '....KKGGGGKK....',
      '...KGGGGGGGGK...',
      '..KGGCGGGGCGGK..',
      '..KGGGGGGGGGGK..',
      '..KGGGGGGGGGGK..',
      '...KGGGGGGGGK...',
      '....KGK..KGK....',
      '....KGK..KGK....',
      '....KKK..KKK....',
    ],
  },
  {
    id: 'starship',
    name: 'COMET CRUISER',
    rarity: 'epic',
    bg: 'linear-gradient(135deg,#b83dff,#ff2e63)',
    pixels: [
      '........K.......',
      '.......KSK......',
      '......KSWSK.....',
      '.....KSWCWSK....',
      '....KSWCCCWSK...',
      '...KSWCCWCCWSK..',
      '..KSSSCCCCCCSSSK',
      '.KSSDDCCKKCCDDSSK',
      'KSSSDDDDKDDDDSSSK',
      '.KSSSSSSKSSSSSSK.',
      '..KKSSSKKKSSSKK..',
      '...KOYOKKKOYOK...',
      '....KYYKYKYYK....',
      '.....KOKKKOK....',
      '......K.K.K.....',
      '......Y.Y.Y.....',
    ],
  },
  {
    id: 'princess',
    name: 'SPACE PRINCESS',
    rarity: 'epic',
    bg: 'linear-gradient(135deg,#ff9ec7,#b83dff)',
    pixels: [
      '.....KKKKKK.....',
      '....KTTTTTTK....',
      '...KTYYYYYTK....',
      '..KTYWYYWYYTK...',
      '..KEEWEEWEEK....',
      '..KEWEEEEWEK....',
      '...KEEKKEEK.....',
      '....KEEEEK......',
      '...KWWWWWWK.....',
      '..KWRRWWRRWK....',
      '..KWWWRRWWWK....',
      '..KWWRRRRWWK....',
      '..KWWWWWWWWK....',
      '...KWW..WWK.....',
      '...KEE..EEK.....',
      '...KKK..KKK.....',
    ],
  },
  {
    id: 'yoda',
    name: 'LIL MASTER',
    rarity: 'legendary',
    bg: 'linear-gradient(135deg,#ffd93d,#3ce67a)',
    pixels: [
      '..GG........GG..',
      '.GGGG......GGGG.',
      '..GGGGGGGGGGGG..',
      '.GGKGGGGGGGGKGG.',
      '.GGGKWGGGGWKGGG.',
      '.GGGWKGGGGKWGGG.',
      '.GGGGGKRRKGGGGG.',
      '..GGGGGGGGGGGG..',
      '...KTTTTTTTTK...',
      '..KTTWTTTTWTTK..',
      '..KTTTTTTTTTTK..',
      '..KTTTTTTTTTTK..',
      '...KTTTTTTTTK...',
      '....KTK..KTK....',
      '....KTK..KTK....',
      '....KKK..KKK....',
    ],
  },
  {
    id: 'bot',
    name: 'BEEP-BOT',
    rarity: 'legendary',
    bg: 'linear-gradient(135deg,#4cf1ff,#3da5ff)',
    pixels: [
      '.......KK.......',
      '......KCCK......',
      '.....KCCCCK.....',
      '....KKKKKKKK....',
      '...KDDDDDDDDK...',
      '..KDDCCDDCCDDK..',
      '..KDDCWDDWCDDK..',
      '..KDDDDRRDDDDK..',
      '..KDDDDDDDDDDK..',
      '..KDSSSSSSSSDK..',
      '...KDDDDDDDDK...',
      '....KDDDDDDK....',
      '...KYK....KYK...',
      '...KYK....KYK...',
      '...KOK....KOK...',
      '...KKK....KKK...',
    ],
  },
];
